#ifndef ERRORCODES_H
#define ERRORCODES_H

enum PdfExtractorError {
    SUCCESS = 1000,
    PDFTK_COMMAND_FAILED = 2001,
    PDFTOTEXT_COMMAND_FAILED = 2002,
    INPUT_PDF_NOT_FOUND = 3001,
    OUTPUT_PDF_WRITE_ERROR = 3002,
    TEMP_FILE_IO_ERROR = 3003,
    INVALID_PAGE_RANGE_FORMAT = 4001,
    INVALID_KEYWORD_INPUT = 4002,
    INVALID_DATE_INPUT_FORMAT = 4003,
    NO_PAGES_EXTRACTED = 5001,
    WATERMARK_PDF_CREATION_FAILED = 5002,
    PDFTOTEXT_NOT_INSTALLED = 2003, // Added this error code
    PDFTK_NOT_INSTALLED = 2004, // Added this error code
    UNKNOWN_ERROR = 9999
};

#endif // ERRORCODES_H